### ISSUE TITLE
Data from PHEV version not available

### ISSUE THREAD

**Issue by rechin304** [hokus15/IOTConnect#10]
Hi, it looks like is only working reliable for EV version.
Can you please let me know what do i need to change to make it work on PHEV?
For example:
I can read odometer, TPMS data, external temp, but nothing regarding VIN or BMS.

Thanks in advance.

**Comment by hokus15** [comment]
Hi,
You need to know the correct PIDs. There is a good repository with information for different pids and models in https://github.com/JejuSoul/OBD-PIDs-for-HKMC-EVs.

With the info in the repo below you can use as a base the monitor for ioniqev -> https://github.com/hokus15/IOTConnect/tree/master/iotconnect/monitors/ioniqev

I hope that helps.

**Comment by rechin304** [comment]
Thanks. I noticed that battery data is only available only when the car is charging. Strange. I will investigate more.
