### ISSUE TITLE
Config.json Example + Execution of Script doesn't work

### ISSUE THREAD

**Issue by Hartmut01** [hokus15/IOTConnect#4]
Hello,
Thank you a lot for making this Project for the Ioniq. :)
I'm am trying to get IOTConnect running on my Raspberry but I have a few difficulties.

My Setup:
I have a OBD Dongle which is working with my EvNotify App on the Phone.
Hotspot on the Phone and Raspberry Pi Zero W running your Script, Node Red and Mosquitto mqtt broker.
I do not have a GPS Antenna so only the Ioniq monitor is what I want to get running for the moment.

I'm trying to follow your "Getting started" and Tutorial but am having problems with the execution of the script.
The Command `python3 -m /opt/IOTConnect/iotconnect`  gives me the error: `/usr/local/bin/python3.8: No module named /opt/IOTConnect/iotconnect`
Can you help me with this issue? Probably nothing in your Script but related to me not knowing python very well. 

Scecond uncertanty for me is the config.josn file. I don't see any example of how to insert the monitors or publishers.
Below is my try of monitoring the Ioniq and publishing through mqtt.
Is it possible to publish without User and Password or do I need to configure this in my mqtt broker?
Is the Broker "localhost" possible? 
```
{
    "publishers":[
        {
            "class": "iotconnect.publishers.mqtt.MQTTPublisher",
            "broker": "localhost",
            "port": 1883,
            "topic_prefix": "Ioniq/",
            "connection_retries": 3,
            "qos": 1,
            "retain": true
         }
    ],
    "monitors":[
        {
            "class": "iotconnect.monitors.noop.NoopMonitor",
            "interval": 10
        }

	{  
	    "class": "iotconnect.monitors.ioniqev.IoniqEVMonitor",
	    "interval": 5
        }
    ]
}
```

Thanks a lot in advance for your script and the work you have already done in this project :)

**Comment by hokus15** [comment]
Hi,
First you can only have the ODB dongle connected with one device at the same time. So you either you need to connect to the phone or the Raspberry Pi.

If you try to run the script manually from the command line make sure you are in the /opt/IOTConnect `cd /opt/IOTConnect` folder and execute the command:

`python3 -m iotconnect`

I need to update the documentation thanks for poiting it.

Regarding the config file:
As a json array you need to separate every object with the comma character `,`.
So the monitors part will be:
`
    "monitors":[
        {
            "class": "iotconnect.monitors.noop.NoopMonitor",
            "interval": 10
        },
	{  
	    "class": "iotconnect.monitors.ioniqev.IoniqEVMonitor",
	    "interval": 5
        }
    ]
`

But my recommendation is that you remove the NoopMonitor as it does nothing (it's only for demonstration purposes) so the monitors part will be like this:
`
    "monitors":[
 	{  
	    "class": "iotconnect.monitors.ioniqev.IoniqEVMonitor",
	    "interval": 5
        }
    ]
`
Regarding the MQTT part right now it only supports secure connection with login and password. It should be possible to connect to any secure login/password protected MQTT broker (so you could connect to localhost).

I hope that helps, feel free to contact me if you have more doubts or problems.
Regards
Jordi

**Comment by hokus15** [comment]
As no other questions I'll close the issue.
